const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf8');

const target1 = `htmlCode = '<!DOCTYPE html><html><head><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-slate-900 text-white p-6"><h2 class="text-2xl font-bold text-blue-400 mb-4">Simulasi Ketumpatan (Demo)</h2><div class="flex flex-col md:flex-row gap-6"><div class="w-full md:w-1/3 bg-slate-800 p-4 rounded-xl border border-slate-700"><label class="block text-sm font-bold mb-2">Pilih Cecair:</label><select id="liquid" class="w-full bg-slate-900 p-2 rounded border border-slate-600 mb-4"><option value="1.0">Air (1.0)</option><option value="0.9">Minyak (0.9)</option><option value="1.4">Madu (1.4)</option></select><label class="block text-sm font-bold mb-2">Jatuhkan Bahan:</label><div class="flex gap-2"><button onclick="drop(\\'Gabus\\', 0.24)" class="flex-1 bg-orange-700 p-2 rounded">Gabus</button><button onclick="drop(\\'Besi\\', 7.87)" class="flex-1 bg-slate-500 p-2 rounded">Besi</button></div><button onclick="resetSim()" class="w-full mt-4 bg-red-600 p-2 rounded">Reset</button></div><div class="w-full md:w-2/3 h-64 bg-slate-950 rounded-xl relative border border-slate-800 flex justify-center items-end p-8"><div id="beaker" class="w-48 h-56 border-4 border-t-0 border-blue-900 rounded-b-2xl relative overflow-hidden flex flex-col justify-end"><div id="water" class="w-full h-1/2 bg-blue-500/30 border-t-2 border-blue-400"></div><div id="objects" class="absolute inset-0"></div></div></div></div><table class="w-full mt-6 text-sm border border-slate-700"><thead class="bg-slate-800"><tr><th class="p-2 border">Bahan</th><th class="p-2 border">Keputusan</th></tr></thead><tbody id="results"></tbody></table><script>function drop(n,d){const l=parseFloat(document.getElementById(\\'liquid\\').value);const r=d>l?\\'Tenggelam\\':\\'Terapung\\';const o=document.createElement(\\'div\\');o.className=\\'absolute text-xs text-center\\';o.style.left=(Math.random()*60+20)+\\'%\\';o.style.top=r===\\'Terapung\\'?\\'40%\\':\\'80%\\';o.innerHTML=\\'<div class="bg-black/50 px-1 rounded">\\'+n+\\'</div><div class="w-8 h-8 rounded \\'+(n===\\'Gabus\\'?\\'bg-orange-700\\':\\'bg-slate-500\\')+\\'"></div>\\';document.getElementById(\\'objects\\').appendChild(o);const tr=document.createElement(\\'tr\\');tr.innerHTML=\\'<td class="p-2 border">\\'+n+\\'</td><td class="p-2 border">\\'+r+\\'</td>\\';document.getElementById(\\'results\\').appendChild(tr)}function resetSim(){document.getElementById(\\'objects\\').innerHTML=\\'\\';document.getElementById(\\'results\\').innerHTML=\\'\\'}</script></body></html>';`;

const replace1 = target1.replace(/\\'/g, "\\\\'");

const target2 = `htmlCode = '<!DOCTYPE html><html><head><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-slate-900 text-white p-6"><h2 class="text-2xl font-bold text-fuchsia-400 mb-4">Bandul Ringkas (Demo)</h2><div class="flex flex-col md:flex-row gap-6"><div class="w-full md:w-1/3 bg-slate-800 p-4 rounded-xl border border-slate-700"><label class="block text-sm mb-1">Panjang: <span id="lenVal">50</span>cm</label><input type="range" id="len" min="20" max="100" value="50" oninput="document.getElementById(\\'lenVal\\').innerText=this.value" class="w-full mb-4"><button id="btn" onclick="toggle()" class="w-full bg-fuchsia-600 p-3 rounded-xl font-bold">MULA</button><div class="grid grid-cols-2 gap-4 mt-4 text-center"><div class="bg-slate-950 p-2 rounded border border-slate-700"><div class="text-[10px]">MASA (s)</div><div id="time" class="text-xl font-mono text-fuchsia-400">0.00</div></div><div class="bg-slate-950 p-2 rounded border border-slate-700"><div class="text-[10px]">AYUNAN</div><div id="count" class="text-xl font-mono text-emerald-400">0/10</div></div></div></div><div class="w-full md:w-2/3 h-64 bg-slate-950 rounded-xl relative overflow-hidden flex justify-center"><div id="pend" class="absolute top-0 origin-top" style="height:150px"><div class="w-0.5 h-full bg-slate-300 mx-auto"></div><div class="w-6 h-6 bg-pink-500 rounded-full -mt-3 mx-auto"></div></div></div></div><script>let r=false,s,req;function toggle(){const b=document.getElementById(\\'btn\\');if(r){cancelAnimationFrame(req);r=false;b.innerText=\\'MULA\\';return}r=true;b.innerText=\\'BERHENTI\\';s=performance.now();const l=document.getElementById(\\'len\\').value;const p=2*Math.PI*Math.sqrt(l/100/9.81);function animate(t){const e=(t-s)/1000;const a=-0.5*Math.cos((2*Math.PI/p)*e);document.getElementById(\\'pend\\').style.transform=\\'rotate(\\'+a+\\'rad)\\';document.getElementById(\\'time\\').innerText=e.toFixed(2);const o=Math.floor(e/p);document.getElementById(\\'count\\').innerText=Math.min(10,o)+\\'/10\\';if(o>=10){r=false;b.innerText=\\'MULA\\';return}req=requestAnimationFrame(animate)}req=requestAnimationFrame(animate)}</script></body></html>';`;

const replace2 = target2.replace(/\\'/g, "\\\\'");

if (code.includes(target1) && code.includes(target2)) {
  code = code.replace(target1, replace1).replace(target2, replace2);
  fs.writeFileSync('src/App.tsx', code);
  console.log('Fixed quotes in App.tsx');
} else {
  console.log('Target strings not found');
}
